# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 637593e221689a4a244f241d40f73cef95dac8c28e5d537438b3ca59f8dc119f8caf5033458abb66c1d5fc0f1f45cb24f7dac29ea7794dfaa02d72539dfc158b

test:
  secret_key_base: 25db000010a03116338b4f1d6784e9335c15b097a0749f8b59962a978e1e1b1bbad8c0f2cd96bf6d10ee78a0133da745bdd1669f29ce01b0f5ecd12b9d0db601

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
